export {
  FloatBoundBuilder,
  IntBoundBuilder,
  type IntBoundConfigurator,
  IntBoundRangeBuilder,
  type IntBoundRangeConfigurator,
  NumberBound,
  NumberBoundData,
  type NumberBoundInput,
  type NumberBoundType,
  type NumberBoundValue,
  SNBT_FLOAT_MAX,
  SNBT_FLOAT_MIN,
  SNBT_FLOAT_MIN_POSITIVE,
} from "#/models/predicates/common/byte-bound.ts";
